spring.application.name=bootfinal

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %thread %-5level %logger{36} - %msg%n
logging.file.name=logs/app.log

application.name= Spring Boot Task Manager
application.version=1.6.9
application.tasks-size=14
application.admin-email=admin@gmail.com

spring.profiles.active=dev

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Spring Boot Task Manager
info.app.version=1.6.9
info.app.author=Samir

